### ISSUE TITLE
brew 下载链接404

### ISSUE THREAD

**Issue by augusl** [anhoder/homebrew-go-musicfox#1]
anhoder/go-musicfox/go-musicfox (v2.1.0) < 2.1.1
==> Upgrading 1 outdated package:
anhoder/go-musicfox/go-musicfox v2.1.0 -> 2.1.1
==> Downloading https://github.com/anhoder/go-musicfox/releases/v2.1.1/go-musicfox_2.1.1_darwin_amd64
##O#- #
curl: (22) The requested URL returned error: 404
Error: go-musicfox: Failed to download resource "go-musicfox"
Download failed: https://github.com/anhoder/go-musicfox/releases/v2.1.1/go-musicfox_2.1.1_darwin_amd64.zip

**Comment by anhoder** [comment]
fixed.
